apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dotnet9224github
  janus-idp.io/tekton: dotnet9224github
  backstage.io/kubernetes-id: dotnet9224github
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dotnet9224github
resources:
- deployment.yaml
- route.yaml
- service.yaml
