apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: dotnet9224github
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnet9224github 
  name: dotnet9224github
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dotnet9224github
    weight: 100 
